AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3BucketEnabled:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        RestrictPublicBuckets: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
      # versioning is great
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketSpaces:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        RestrictPublicBuckets: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True

      # versioning is great

      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FlowBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-flowlogs"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::AccountId}-flowlogs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        RestrictPublicBuckets: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
      VersioningConfiguration:
        Status: Enabled

  #############
  ###  IAM  ###
  #############

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: "user"
