AWSTemplateFormatVersion: '2010-09-09'

Resources:
  S3BucketEnabled:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
      # versioning is great
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: team
          Value: asd
  S3BucketSpaces:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True

      # versioning is great

      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: team
          Value: asd
  FlowBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-flowlogs"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::AccountId}-flowlogs"
        - Key: team
          Value: asd

  #############
  ###  IAM  ###
  #############
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: "user"
      Tags:
        - Key: team
          Value: asd
